package othelo;

import java.awt.BorderLayout;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JOptionPane;
import java.awt.Font;

public class Othello_Panel extends javax.swing.JPanel implements Observer{

	
	/** the board */
	private Board array_board;
	
    /** Creates new form OthelloPanel */
    public Othello_Panel() {
        initComponents();

        
        init();
    }
    
    /** Add board */
    private void init() {
    	array_board = new Board();
		this.add(array_board, BorderLayout.CENTER);
		
		Othello.getInstance().addObserver(this);
		Othello.getInstance().newGame();
    }
    
    /** Sets status message */
    public void setMessage(String msg) {
    	lblStatus.setText(msg);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();

        setForeground(new java.awt.Color(242, 17, 39));
        setLayout(new java.awt.BorderLayout());

        lblStatus.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 0, 0));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText("lblStatus");
        add(lblStatus, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

	@Override
	public void update(Observable arg0, Object arg1) {
		Othello OthelloGame = Othello.getInstance();
		
		switch (OthelloGame.getGameState()) {
		case Othello.play:
			setMessage("White " + OthelloGame.getWhiteScore() + " - " + OthelloGame.getBlackScore() + " Black");
			array_board.repaint();
			break;
		case Othello.end:
			String msg = "";
			int blackScore = OthelloGame.getBlackScore();
			int whiteScore = OthelloGame.getWhiteScore();
			if (blackScore > whiteScore)
				msg = "Black win: " + blackScore + " - " + whiteScore;
			else if (blackScore < whiteScore)
				msg = "White win: " + whiteScore + " - " + blackScore;
			else
				msg = "Draw: " + blackScore + " - " + whiteScore;
			JOptionPane.showMessageDialog(this, msg);
			break;
		}
		
	}

}
