
package othelo;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;

import javax.swing.UIManager;


public class Othello_Frame extends javax.swing.JFrame {

	private Othello_Panel OthelloPanel;
        private JFrame jFrame = new JFrame("frame1");
	
	/** Creates new form Othello */
        public Othello_Frame() 
        {
            initComponents();


            // add Othello panel
            OthelloPanel = new Othello_Panel();
            this.add(OthelloPanel, BorderLayout.CENTER);
            pack();
            setLocationRelativeTo(null);
            //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            //Point middle = new Point(screenSize.width / 2, screenSize.height / 2);
            //Point newLocation = new Point(middle.x - (jFrame.getWidth() / 2), middle.y - (jFrame.getHeight() / 2));
            //jFrame.setLocation(newLocation);
        }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: 	Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        mnuNewGame = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reversi");
        setResizable(false);

        gameMenu.setText("Game");

        mnuNewGame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuNewGame.setText("New...");
        mnuNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewGameActionPerformed(evt);
            }
        });
        gameMenu.add(mnuNewGame);

        jMenuBar.add(gameMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewGameActionPerformed
    	NewGameDialog newGameDialog = new NewGameDialog();
    	newGameDialog.setVisible(true);
    }//GEN-LAST:event_mnuNewGameActionPerformed
    
   
    public static void main(String args[]) 
    {
    	
    	
        try {
		UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		
            } 
        catch (Exception e) {}
		
        java.awt.EventQueue.invokeLater
        (new Runnable() 
                    {
                        public void run() 
                        {
                            new Othello_Frame().setVisible(true);
                        }
                    }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem mnuNewGame;
    // End of variables declaration//GEN-END:variables

}
